In [10]:
# faiss 的简单demo

In [11]:
# 到这里安装自己版本的faiss
# https://anaconda.org/search?q=faiss

In [12]:
import numpy as np

In [13]:
d = 64                           # 维度
nb = 100000                      # 数据库数据大小

In [14]:
np.random.seed(1234)             # 保证可以复现

In [15]:
# 随机生成nb个维度为d的list
xb = np.random.random((nb, d)).astype('float32')

In [16]:
xb.shape

(100000, 64)

In [17]:
xb[:, 0] += np.arange(nb) / 1000.

In [18]:
import faiss                  


In [19]:
# 创建索引
index = faiss.IndexFlatL2(d)   

In [20]:
print(index.is_trained)


True


In [21]:
# 添加数据
index.add(xb)                  
print(index.ntotal)

100000


In [22]:
k = 4                          # 搜索4个最近的值
D, I = index.search(xb[:5], k) # 搜索
print(I)
print(D)


[[  0 393 363  78]
 [  1 555 277 364]
 [  2 304 101  13]
 [  3 173  18 182]
 [  4 288 370 531]]
[[0.        7.1751733 7.2076297 7.2511625]
 [0.        6.3235645 6.684581  6.799946 ]
 [0.        5.7964087 6.391736  7.2815123]
 [0.        7.2779055 7.5279875 7.662846 ]
 [0.        6.7638035 7.2951202 7.368815 ]]


In [23]:
# 保存到磁盘
faiss.write_index(index,'test.index')